#   This file is part of Bob.
#
#   Bob is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Bob is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Bob. If not, see <http://www.gnu.org/licenses/>.

version: 2

jobs:
  build:
    working_directory: ~/bob
    docker:
      - image: clojure:boot

    steps:
      - checkout
      - restore_cache:
          key: bob-{{ checksum "build.boot" }}
      - run: boot kaocha build
      - save_cache:
          paths:
            - ~/.m2
          key: bob-{{ checksum "build.boot" }}
      - store_artifacts:
          path: target/bob-standalone.jar
          destination: bob-standalone.jar

  test:
    machine:
      java:
        version: oraclejdk10

    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      BOOT_WATCHERS_DISABLE: "yes"

    steps:
      - checkout
      - run: mkdir -p ~/bin
      - run: export PATH=~/bin:$PATH
      - run: git clone https://github.com/bob-cd/resource-git
      - run: docker build -t resource-git resource-git/
      - run: docker run -p 8000:8000 -d --rm resource-git
      - run: curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh -o ~/bin/boot
      - run: chmod +x ~/bin/boot
      - run: pyenv install 3.6.2
      - run: pyenv local 3.6.2
      - run: python3 integration-tests/run.py

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
