#   This file is part of Bob.
#
#   Bob is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Bob is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Bob. If not, see <http://www.gnu.org/licenses/>.

version: 2

jobs:
  build_test:
    working_directory: ~/bob
    docker:
      - image: clojure:boot

    steps:
      - checkout
      - restore_cache:
          key: bob-{{ checksum "build.boot" }}
      - run:
          name: "Unit tests and build uberjar"
          command: boot kaocha build
      - save_cache:
          paths:
            - ~/.m2
          key: bob-{{ checksum "build.boot" }}
      - store_artifacts:
          path: target/bob-standalone.jar
          destination: bob-standalone.jar

  integration_test_deploy:
    machine: true

    steps:
      - checkout
      - run:
          name: "Integration tests"
          command: |
            cd integration-tests     && \
            docker-compose up -d bob && \
            docker-compose up --abort-on-container-exit --scale bob-node=3 integration-tests
      - run:
          name: "Docker Hub push"
          command: |
            case ${CIRCLE_BRANCH} in
                master)
                    docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
                    docker push bobcd/bob:latest
                    ;;
                *)
                    echo "Not a stable branch, not pushing image."
                    ;;
            esac

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build_test
      - integration_test_deploy:
          context: Docker
          requires:
            - build_test
