openapi: "3.0"

info:
  title: My API
  version: "0.1"
  description: The modular, extensible platform

paths:
  /can-we-build-it:
    get:
      operationId: HealthCheck
      summary: Runs health checks

      responses:
        "200":
          description: Successful health check
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleResponse"
        default:
          description: Health check failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimpleResponse"

  /inc/{amount}:
    post:
      operationId: IncCounter
      summary: Increments the counter by {amount}

      parameters:
        - name: amount
          required: true
          in: path
          description: The amount to increase
          schema:
            type: integer

      responses:
        "200":
          description: Returns the incremented counter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CounterResponse"

  /api.yaml:
    get:
      operationId: GetApiSpec
      summary: Returns the OpenAPI spec

      responses:
        "200":
          description: Returns the spec
          content:
            application/yaml:
              schema:
                type: string

components:
  schemas:
    SimpleResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    CounterResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: object
          required:
            - counter
          properties:
            counter:
              type: integer
